apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hitapp
  template:
    metadata:
      labels:
        app: hitapp
    spec:
      containers:
      - name: hitapp
        image: arnaudessanin/hitapp
        ports:
        - containerPort: 5000
