apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 10.0.4.6
