apiVersion: v1
kind: Service
metadata:
  name: hitapp-loadbalancer
spec:
  selector:
    app: hitapp
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 5000
  type: LoadBalancer
  externalIPs:
    - 10.0.4.6
